#Important note : All paths definded in this configuration file must be either absolute or relative to the location of the Snakefile

## Path to existing reference file
reference_genome: input/reference_genome/nCoV-2019.reference.fasta

## Path to existing folder with fastq files
input_folder : input/01_raw_data/
extension : fastq

## Path to existing metadata file
metadata : input/coldata.csv

## Path to the results folder 
output_folder : results/
