#Important note : All paths definded in this configuration file must be either absolute or relative to the location of the Snakefile


## Path to existing reference file
reference_genome: 00-reference-genome/nCoV-2019.reference.fasta

## Path to existing metadata
metadata : coldata.csv

## Sample name 
sample:
    - SRR12881613_1
    - SRR12881614_1
    - SRR12881615_1
