#Important note : All paths definded in this configuration file must be either absolute or relative to the location of the Snakefile

## Path to existing reference file
reference_genome: 00-reference-genome/nCoV-2019.reference.fasta

## Path to existing metadata
metadata : 00-metadata/coldata.csv

## Sample names
sample:
    - SRR12881620_subseq
    - SRR12881621_subseq
    - SRR12881622_subseq
